apiVersion: v1
kind: Secret
metadata:
  name: teachers-secrets
type: Opaque
data:
  mongoose: bW9uZ29kYitzcnY6Ly9tYW5rbGF1czo0OEtyRDIwZXpmTnpaZGpzQGNsdXN0ZXIwLmR3d29nM3kubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
