apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-teacher
  labels:
    app: ms-teacher
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-teacher
  template:
    metadata:
      labels:
        app: ms-teacher
    spec:
      containers:
        - name: ms-teacher
          image: aymenboujmil/ms-teachers
          env:
            - name: MONGOOSE_CONNECT
              valueFrom:
                secretKeyRef:
                  name: teachers-secrets
                  key: mongoose
            - name: PORT
              value: "5050"
          ports:
            - containerPort: 5050
      restartPolicy: Always
